version: '3.9'
services:
    investor_database:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
        ports:
            - "${DATABASE_EXTERNAL_PORT}:${DATABASE_INTERNAL_PORT}"
        networks:
            - investor-network

    investor_php:
        image: investor/php
        build:
            context: ../.
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                PROJECT_ROOT_DIRECTORY: ${PROJECT_ROOT_DIRECTORY}
                PROJECT_DATA_DIRECTORY: ${PROJECT_DATA_DIRECTORY}
                COMPOSER_AUTH_TOKEN: ${GITHUB_AUTH_TOKEN}
                SYMFONY_CLI_VERSION: ${SYMFONY_CLI_VERSION}
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - PROJECT_DATA_DIRECTORY=${PROJECT_DATA_DIRECTORY}
        volumes:
            - ../app:${PROJECT_ROOT_DIRECTORY}
        networks:
            - investor-network

    investor_nginx:
        image: investor/nginx
        build:
            context: ./nginx
            args:
                NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
                PROJECT_ROOT_DIRECTORY: ${PROJECT_ROOT_DIRECTORY}
                PROJECT_DATA_DIRECTORY: ${PROJECT_DATA_DIRECTORY}
                PHP_UPSTREAM_CONTAINER: frontend_php
                PHP_UPSTREAM_PORT: 9000
        environment:
            - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
            - PROJECT_ROOT_DIRECTORY=${PROJECT_ROOT_DIRECTORY}
            - PROJECT_DATA_DIRECTORY=${PROJECT_DATA_DIRECTORY}
            - PHP_UPSTREAM_CONTAINER=investor_php
            - PHP_UPSTREAM_PORT=9000
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - investor_php
        volumes:
            - ../app:${PROJECT_ROOT_DIRECTORY}
        networks:
            - investor-network

networks:
    investor-network:
        external: true
